[package]
edition = "2024"
name = "hamming_distance_experiments"
version = "0.1.0"

[[bin]]
name = "hamming_main"
path = "src/main.rs"

[lib]
name = "hamming"

[dependencies]

[dev-dependencies]
criterion = "*"
simsimd = "6.2.1"
triple_accel = "*"

[[bench]]
harness = false
name = "criterion"
